# Tarea 2

Autor: Diego Prado

In [33]:
import os
import polars as pl
from polars import DataFrame
import plotly.express as px
import plotly.io as pio
from dash_bootstrap_templates import load_figure_template
from path import Path
import json
import numpy as np

#Paquetería para pruebas estadisticas
from scipy.stats import skew, kurtosis

#Paqueterías de limpieza de datos
from sklearn.impute import SimpleImputer

## Confuguraciones

In [2]:
pio.renderers.default = 'iframe'
load_figure_template("minty_dark")

## Funciones

In [3]:
def report_nulls(df: DataFrame) -> DataFrame:
    """
    Generamos un reporte de nulos de los datos.
    """
    cols = df.columns
    report = {
        "columns":[],
        "nulls":[]
    }
    
    for col in cols:
        nulos = df[col].is_null().sum()
        if nulos > 0:
            report.get("columns").append(col)
            report.get("nulls").append(nulos)
    
    report = pl.DataFrame(report)
    report = report.with_columns(
        prc_nulls = pl.col("nulls") / df.shape[0] * 100
    )

    return report

In [4]:
def plot_nulls(df: DataFrame) -> None:
    """
    Graficamos los nulos de los dataframes.
    """

    fig = px.bar(
        df, 
        x="prc_nulls", 
        y="columns", 
        title="Porcentaje de Valores Nulos por Columna",
        text_auto=True,
        height=800,
        width=900,
        range_x=[0,100]
    )

    fig.show()

## Limpieza de datos

In [5]:
p = Path('data')

df = pl.read_csv(p / 'raw' / 'FIFA19-DS.csv')
df.head()

shape: (5, 76)
┌────────┬─────┬─────────┬───────────┬───┬────────────┬────────────────┬───────────┬──────────┐
│ ID     ┆ Age ┆ Overall ┆ Potential ┆ … ┆ GKReflexes ┆ Preferred Foot ┆ Body Type ┆ Position │
│ ---    ┆ --- ┆ ---     ┆ ---       ┆   ┆ ---        ┆ ---            ┆ ---       ┆ ---      │
│ i64    ┆ i64 ┆ i64     ┆ i64       ┆   ┆ i64        ┆ str            ┆ str       ┆ str      │
╞════════╪═════╪═════════╪═══════════╪═══╪════════════╪════════════════╪═══════════╪══════════╡
│ 158023 ┆ 31  ┆ 94      ┆ 94        ┆ … ┆ 8          ┆ Left           ┆ Lean      ┆ ST       │
│ 20801  ┆ 33  ┆ 94      ┆ 94        ┆ … ┆ 11         ┆ Right          ┆ Normal    ┆ ST       │
│ 190871 ┆ 26  ┆ 92      ┆ 93        ┆ … ┆ 11         ┆ Right          ┆ Lean      ┆ AM       │
│ 192985 ┆ 27  ┆ 91      ┆ 92        ┆ … ┆ 13         ┆ Right          ┆ Normal    ┆ MF       │
│ 183277 ┆ 27  ┆ 91      ┆ 91        ┆ … ┆ 8          ┆ Right          ┆ Normal    ┆ ST       │
└────────┴─────┴─────────┴───────────┴───┴────────────┴────────────────┴───────────┴──────────┘

In [35]:
df.describe()

shape: (9, 77)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ ID        ┆ Age       ┆ Overall   ┆ … ┆ GKReflexe ┆ Preferred ┆ Body Type ┆ Position │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ s         ┆ Foot      ┆ ---       ┆ ---      │
│ str       ┆ f64       ┆ f64       ┆ f64       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ f64       ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 17140.0   ┆ 17140.0   ┆ 17140.0   ┆ … ┆ 17140.0   ┆ 17140     ┆ 17140     ┆ 17140    │
│ null_coun ┆ 0.0       ┆ 0.0       ┆ 0.0       ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 214049.43 ┆ 25.150117 ┆ 66.371937 ┆ … ┆ 16.485414 ┆ null      ┆ null      ┆ null     │
│           ┆ 1855      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ std       ┆ 30013.910 ┆ 4.658667  ┆ 6.925482  ┆ … ┆ 17.668488 ┆ null      ┆ null      ┆ null     │
│           ┆ 983       ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ min       ┆ 16.0      ┆ 16.0      ┆ 46.0      ┆ … ┆ 1.0       ┆ Left      ┆ Lean      ┆ AM       │
│ 25%       ┆ 199940.0  ┆ 21.0      ┆ 62.0      ┆ … ┆ 8.0       ┆ null      ┆ null      ┆ null     │
│ 50%       ┆ 221603.0  ┆ 25.0      ┆ 66.0      ┆ … ┆ 11.0      ┆ null      ┆ null      ┆ null     │
│ 75%       ┆ 236304.0  ┆ 28.0      ┆ 71.0      ┆ … ┆ 14.0      ┆ null      ┆ null      ┆ null     │
│ max       ┆ 246620.0  ┆ 44.0      ┆ 94.0      ┆ … ┆ 94.0      ┆ Right     ┆ Stocky    ┆ ST       │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [6]:
df.is_duplicated().sum()

0

In [7]:
plot_nulls(report_nulls(df))

In [12]:
fig = px.bar(
    df.group_by("Position").agg(pl.col('ID').count()),
    x="Position",
    y="ID",
    title="Total de Jugadores por posición",
    text_auto=True
)

fig.show()

In [45]:
null_columns = report_nulls(df)["columns"].to_list()

df.group_by("Position").agg(
    [pl.col(c).is_null().sum().alias(f"{c}_nulls") for c in null_columns]
)

shape: (6, 27)
┌──────────┬──────────┬──────────┬──────────┬───┬───────────┬──────────┬───────────┬──────────┐
│ Position ┆ LS_nulls ┆ ST_nulls ┆ RS_nulls ┆ … ┆ LCB_nulls ┆ CB_nulls ┆ RCB_nulls ┆ RB_nulls │
│ ---      ┆ ---      ┆ ---      ┆ ---      ┆   ┆ ---       ┆ ---      ┆ ---       ┆ ---      │
│ str      ┆ u32      ┆ u32      ┆ u32      ┆   ┆ u32       ┆ u32      ┆ u32       ┆ u32      │
╞══════════╪══════════╪══════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪══════════╡
│ DF       ┆ 0        ┆ 0        ┆ 0        ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 0        │
│ ST       ┆ 0        ┆ 0        ┆ 0        ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 0        │
│ AM       ┆ 0        ┆ 0        ┆ 0        ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 0        │
│ GK       ┆ 1842     ┆ 1842     ┆ 1842     ┆ … ┆ 1842      ┆ 1842     ┆ 1842      ┆ 1842     │
│ DM       ┆ 0        ┆ 0        ┆ 0        ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 0        │
│ MF       ┆ 0        ┆ 0        ┆ 0        ┆ … ┆ 0         ┆ 0        ┆ 0         ┆ 0        │
└──────────┴──────────┴──────────┴──────────┴───┴───────────┴──────────┴───────────┴──────────┘

In [49]:
df_sin_porteros = df.filter(pl.col("Position") != "GK")
df_sin_porteros.describe()

shape: (9, 77)
┌────────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic  ┆ ID        ┆ Age      ┆ Overall   ┆ … ┆ GKReflexe ┆ Preferred ┆ Body Type ┆ Position │
│ ---        ┆ ---       ┆ ---      ┆ ---       ┆   ┆ s         ┆ Foot      ┆ ---       ┆ ---      │
│ str        ┆ f64       ┆ f64      ┆ f64       ┆   ┆ ---       ┆ ---       ┆ str       ┆ str      │
│            ┆           ┆          ┆           ┆   ┆ f64       ┆ str       ┆           ┆          │
╞════════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count      ┆ 15298.0   ┆ 15298.0  ┆ 15298.0   ┆ … ┆ 15298.0   ┆ 15298     ┆ 15298     ┆ 15298    │
│ null_count ┆ 0.0       ┆ 0.0      ┆ 0.0       ┆ … ┆ 0.0       ┆ 0         ┆ 0         ┆ 0        │
│ mean       ┆ 214768.08 ┆ 25.05334 ┆ 66.588704 ┆ … ┆ 10.514185 ┆ null      ┆ null      ┆ null     │
│            ┆ 5175      ┆          ┆           ┆   ┆           ┆           ┆           ┆          │
│ std        ┆ 28616.882 ┆ 4.542381 ┆ 6.797187  ┆ … ┆ 3.105028  ┆ null      ┆ null      ┆ null     │
│            ┆ 947       ┆          ┆           ┆   ┆           ┆           ┆           ┆          │
│ min        ┆ 16.0      ┆ 16.0     ┆ 46.0      ┆ … ┆ 1.0       ┆ Left      ┆ Lean      ┆ AM       │
│ 25%        ┆ 200610.0  ┆ 21.0     ┆ 62.0      ┆ … ┆ 8.0       ┆ null      ┆ null      ┆ null     │
│ 50%        ┆ 221768.0  ┆ 25.0     ┆ 67.0      ┆ … ┆ 10.0      ┆ null      ┆ null      ┆ null     │
│ 75%        ┆ 236374.0  ┆ 28.0     ┆ 71.0      ┆ … ┆ 13.0      ┆ null      ┆ null      ┆ null     │
│ max        ┆ 246620.0  ┆ 41.0     ┆ 94.0      ┆ … ┆ 37.0      ┆ Right     ┆ Stocky    ┆ ST       │
└────────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [52]:
df_limpio = df_sin_porteros.drop(["Age", "Overall", "Potential", "Value", "Wage", "Preferred Foot", "International Reputation"])
df_limpio

shape: (15_298, 69)
┌────────┬─────────┬───────────┬─────────────┬───┬─────────────┬────────────┬───────────┬──────────┐
│ ID     ┆ Special ┆ Weak Foot ┆ Skill Moves ┆ … ┆ GKPositioni ┆ GKReflexes ┆ Body Type ┆ Position │
│ ---    ┆ ---     ┆ ---       ┆ ---         ┆   ┆ ng          ┆ ---        ┆ ---       ┆ ---      │
│ i64    ┆ i64     ┆ i64       ┆ i64         ┆   ┆ ---         ┆ i64        ┆ str       ┆ str      │
│        ┆         ┆           ┆             ┆   ┆ i64         ┆            ┆           ┆          │
╞════════╪═════════╪═══════════╪═════════════╪═══╪═════════════╪════════════╪═══════════╪══════════╡
│ 158023 ┆ 2202    ┆ 4         ┆ 4           ┆ … ┆ 14          ┆ 8          ┆ Lean      ┆ ST       │
│ 20801  ┆ 2228    ┆ 4         ┆ 5           ┆ … ┆ 14          ┆ 11         ┆ Normal    ┆ ST       │
│ 190871 ┆ 2143    ┆ 5         ┆ 5           ┆ … ┆ 15          ┆ 11         ┆ Lean      ┆ AM       │
│ 192985 ┆ 2281    ┆ 5         ┆ 4           ┆ … ┆ 10          ┆ 13         ┆ Normal    ┆ MF       │
│ 183277 ┆ 2142    ┆ 4         ┆ 4           ┆ … ┆ 8           ┆ 8          ┆ Normal    ┆ ST       │
│ …      ┆ …       ┆ …         ┆ …           ┆ … ┆ …           ┆ …          ┆ …         ┆ …        │
│ 243413 ┆ 1098    ┆ 3         ┆ 2           ┆ … ┆ 11          ┆ 13         ┆ Lean      ┆ DF       │
│ 243165 ┆ 1098    ┆ 2         ┆ 2           ┆ … ┆ 5           ┆ 12         ┆ Normal    ┆ ST       │
│ 241638 ┆ 1189    ┆ 3         ┆ 2           ┆ … ┆ 6           ┆ 13         ┆ Normal    ┆ ST       │
│ 246268 ┆ 1228    ┆ 3         ┆ 2           ┆ … ┆ 8           ┆ 9          ┆ Lean      ┆ AM       │
│ 246269 ┆ 1321    ┆ 3         ┆ 2           ┆ … ┆ 12          ┆ 9          ┆ Lean      ┆ MF       │
└────────┴─────────┴───────────┴─────────────┴───┴─────────────┴────────────┴───────────┴──────────┘